# Trigger the pipeline to run whenever a commit to the main branch is made.
trigger:
- main

# Use a custom agent pool called "Unity Windows" that manages custom agents
# that have the required Unity versions installed and any required SDKs for target platforms
# configured.
pool:
  name: Unity Windows

# Adds a shared pipeline variables library to the pipeline that contains
# authentication variables for activating a Unity editor with a Unity Plus / Pro seat.
variables:
  - group: unity-activation-variables

steps:
# Before we build we activate a Unity Plus/Pro seat on the agent, only for the duration
# of the pipeline execution. That way we can e.g. get rid of the Unity splash screen in our build.
- task: UnityBuildTask@3
  inputs:
    buildTarget: 'standalone'
    outputPath: '$(Build.BinariesDirectory)'
    outputFileName: 'drop'
